### ISSUE TITLE
PHP 8 Fatal error: __destruct(), Warning: Missing arginfo

### ISSUE THREAD

**Issue by webbom** [SeasX/SeasClick#11]
Hello,
Doesn't work for php 8.x

````
# make test
[...]
Build complete.
Don't forget to run 'make test'.
=====================================================================
PHP         : /usr/local/bin/php 
Warning: Missing arginfo for SeasClick_version() in Unknown on line 0

Fatal error: Method SeasClick::__destruct() cannot take arguments in Unknown on line 0
  
---------------------------------------------------------------------
PHP         : /usr/local/bin/phpdbg 
Warning: Missing arginfo for SeasClick_version() in Unknown on line 0

Fatal error: Method SeasClick::__destruct() cannot take arguments in Unknown on line 0

---------------------------------------------------------------------
CWD         : /usr/work/src/SeasClick
Extra dirs  : 
VALGRIND    : Not used
[...]
````

**Comment by Rock-520** [comment]
Could you   provide more infomation about  php version ,  such as  php -v

**Comment by guba-jeckerman** [comment]
Running into the same error


```
php -v

PHP 8.0.14 (cli) (built: Dec 16 2021 11:20:34) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.14, Copyright (c) Zend Technologies
```

**Comment by Rock-520** [comment]
> Running into the same error
> 
> ```
> php -v
> 
> PHP 8.0.14 (cli) (built: Dec 16 2021 11:20:34) ( NTS )
> Copyright (c) The PHP Group
> Zend Engine v4.0.14, Copyright (c) Zend Technologies
> ```

Ok , i wiil fix the bug   before next  weekend

**Comment by Rock-520** [comment]
> Running into the same error
> 
> ```
> php -v
> 
> PHP 8.0.14 (cli) (built: Dec 16 2021 11:20:34) ( NTS )
> Copyright (c) The PHP Group
> Zend Engine v4.0.14, Copyright (c) Zend Technologies
> ```

I  alerady fix the bug , clould you   try once more ?    you can use  SeasClick-0.1.1  tag

**Comment by guba-jeckerman** [comment]
Success, thank you!

**Comment by Kabingeran** [comment]
Hi! Could you update pecl for php 8.x please?
